### ISSUE TITLE
Have you tried to speed MoCo v2 by FFCV? How does it go?

### ISSUE THREAD

**Issue by realliyifei** [kumarkrishna/fastssl#22]
Title. As I saw that you speed SSL by FFCV, e.g. https://github.com/kumarkrishna/fastssl/blob/8f96d16d2a/write_ffcv_double_datasets.py 

Have you tried the same thing on MoCo v2? Since [the issue](https://github.com/vturrisi/solo-learn/issues/298) mentioned in another SSL speeding library implies that adapting FFCV to MoCo v2 is non-trivial.

**Comment by arnaghosh** [comment]
Hi,
Thank you for your interest. :)
We haven't tried MoCo v2 yet. Our current implementation includes SimCLR and BarlowTwins. 
Feel free to add MoCo v2 and open a PR with the changes!

**Comment by realliyifei** [comment]
Thanks! I notice that you write the images as double in ffcv beton file. Would it slow the training or increase the memory significantly?

**Comment by arnaghosh** [comment]
Apologies for the delayed reply @realliyifei! 
That's correct. This might increase the memory requirements and lead to slightly longer data loading at the start because there are more things to read, but I am really not the expert. 
We would probably want to switch to the framework used in this repo eventually: https://github.com/facebookresearch/FFCV-SSL

**Comment by realliyifei** [comment]
Thank you! This library looks very helpful!
